$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
model: azureml:rag-flow-model:1
instance_type: Standard_DS3_v2
instance_count: 1
request_settings:
  request_timeout_ms: 50000
environment_variables:
  # "compute" mode is the default mode, if you want to deploy to serving mode, you need to set this env variable to "serving"
  PROMPTFLOW_RUN_MODE: serving

  # (Optional) Filter the fields to expose in the response.
  # PROMPTFLOW_RESPONSE_INCLUDED_FIELDS: '["answer", "context"]'
