name: CI Pipeline

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md' 

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      # Install pip, pytest and project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt              
      - name: Test with pytest
        env:
          PYTHONPATH: flow
          PYTHONWARNINGS: ignore::DeprecationWarning,ignore::RemovedInMarshmallow4Warning
        run: pytest tests/ --doctest-modules --junitxml=junit/test-results-3.11.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-3.11
          path: junit/test-results-3.11.xml
        if: always()

  build-flow:
    needs: unit-testing
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "TODO: Build Flow"
        shell: bash

  ai-assisted-evaluation:
    needs: build-flow
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "TODO: AI-assisted Evaluation"
        shell: bash
      
  register-flow:
    needs: ai-assisted-evaluation    
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "TODO: Register Flow"
        shell: bash


  # TODO: Call CD pipeline to provision and deploy the application

